name: json_to_dart
version: 0.0.1
author: Javier Lecuona <javierlecuona@gmail.com>
description: A library that generates Dart classes (parse and generator included) from a json string.
homepage: https://github.com/javiercbk/json_to_dart
environment:
  sdk: ">=2.0.0"

dependencies:
  convert: ^3.0.1
  dart_style: ^2.0.2
  clippy: ^1.0.0
  colorize: ^3.0.0
  args: ^2.1.1

dev_dependencies:
  test: "^1.3.0"
  path: "^1.5.1"
